version: "3.7"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: entity_search
    ports:
      - "5432:5432"
    volumes:
      - "./postgres.conf:/etc/postgresql/postgresql.conf"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf


  pulsar:
    image: apachepulsar/pulsar:2.7.1
    hostname: pulsar
    command: bin/pulsar standalone
    ports:
      - "8080:8080"
      - "6650:6650"
    volumes:
      - "./data/:/pulsar/data"
      - "./io_connectors/pulsar-io-debezium-postgres-2.7.1.nar:/pulsar/connectors/pulsar-io-debezium-postgres-2.7.1.nar"
      - "./debezium-postgres-source-config.yaml:/pulsar/conf/debezium-postgres-source-config.yaml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - node.name=es01
      - cluster.name=es-entity-search
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch